# This file specifies your Python application's runtime configuration.
# See https://cloud.google.com/appengine/docs/managed-vms/config for details.

runtime: python38
env: standard
entrypoint: gunicorn -b :$PORT ./flask-server/main:app

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

#[START env]
env_variables:
  # postgresql+psycopg2://USER:PASSWORD@/DATABASE?host=/cloudsql/INSTANCE_CONNECTION_NAME
  # Replace user, password, database, and instance connection name with the values obtained
  # when configuring your Cloud SQL instance.
  # GOOGLE_APPLICATION_CREDENTIALS: ./CrepeNShake-8b4a0f7fb8c9.json
  DB_STRING: >-
    postgresql+psycopg2://postgres:Iqopaogh23!@/postgres?host=/cloudsql/quickbev:us-central1:quckbevdb

#[END env]

#[START cloudsql_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
  cloud_sql_instances: quickbev:us-central1:quckbevdb

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
basic_scaling:
  max_instances: 25
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
#[END cloudsql_settings]
