steps:
    - name: 'gcr.io/cloud-builders/npm'
      args: ['i', 'react-dev-utils', '--save']
      env: ['PROJECT_ROOT=backend']
      dir: 'react-app/src'
    - name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'build']
      env: ['PROJECT_ROOT=backend']
      dir: 'react-app/src'
    - name: 'gcr.io/cloud-builders/npm'
      args: ['i', '-g', 'remove-node-modules']
      env: ['PROJECT_ROOT=backend']
      dir: 'react-app/src'
    - name: 'gcr.io/cloud-builders/'
      args: ['remove-node-modules']
      env: ['PROJECT_ROOT=backend']
